### ISSUE TITLE
Passing ?resource=... does not work on Trifid plugin

### ISSUE THREAD

**Issue by ktk** [zazuko/trifid-plugin-graph-explorer#3]
It looks like passing a resource as an entry point does not work in the Trifid plugin, as in:

`?resource=http://some.iri.that.exists/bla`

Does Trifid hijack that route somehow?

**Comment by semanticfire** [comment]
This is not something internal to Graph Explorer, it is extra code that needs to be in the HTML, I'll fork and do a PR

**Comment by ludovicm67** [comment]
Can someone test if it is working as expected, so that I can close this?
