### ISSUE TITLE
No links between resources

### ISSUE THREAD

**Issue by ktk** [zazuko/trifid-plugin-graph-explorer#4]
On the MOPO instance there are no links rendered between resources:

<img width="499" alt="Screen Shot 2021-10-21 at 13 28 14" src="https://user-images.githubusercontent.com/583021/138268300-c3badd09-283c-408c-9d88-da0782b52898.png">

That is a `rdf:type` relation in between the two.

**Comment by semanticfire** [comment]
How are the resources added to the canvas? manual or programaticaly ?

**Comment by ktk** [comment]
@semanticfire not sure what you mean here. I add them manually in the UI.

Could this problem show up when Graph-explorer is not running from `/` (root)? Maybe some missing resources

**Comment by semanticfire** [comment]
Is this something that I could reproduce?

**Comment by ktk** [comment]
Turns out this is a missing `rdfs` prefix in the SPARQL query that at least Fuseki does not seem to provide/use by default. Can be fixed by adding the prefix to the plugin config.

@semanticfire could you point to where this should be added to the config?
